@startuml
title Livraison d'une commande : Dispatch des commandes
boundary Cron 
control Server
database Order
database OrderLine
database Inventory
database DeliveryMandata
collections Application
actor DeliveryMan
loop Every 3 min
Cron -> Server : Sendorders()
Server -> Order : GetAllPendingOrders
Order --> Server : Orders[]
loop Fetch orders status = waiting_delivery_man
Server -> DeliveryMandata : Get closer delivery man (not contacted yet)
DeliveryMandata --> Inventory : Inventory[]
Inventory --> OrderLine : product[]
OrderLine --> Order : orderLine[]
Order --> Server : DeliveryMan[]
Server -> Application : Push order
Application -> DeliveryMan : Notification
end
end
@enduml