@startuml
title Création d'une commande
actor Client
collections Plats 
collections Commande
actor Banque
loop
Client -> Plats : Consulter les plats
Plats --> Client : Liste des plats
Client -> Plats : Ajouter / supprimer un plat dans le panier
Plats -> Commande : Mise à jour le panier
Commande --> Client : Affiche le montant du panier
end
Client -> Commande : Valider le panier
alt si pas authentifié
    alt si nouveau client
    Commande --> Client : formulaire de création de compte
    Client -> Commande : Saisir : email & mot de passe & n° de téléphone & adresse complète
    Commande --> Client : Demande de vérification par email
    Client -> Commande : Cliquer sur le lien de vérification par email
    else si déjà client
    Commande --> Client : formulaire d'authentification
    Client -> Commande : Saisir : email & mot de passe
    end
end
Commande --> Client : Formulaire de renseignement des infos. de livraison
alt nouvelle adresse (jamais commandé à cette adresse)
Client -> Commande :  Saisir l'adresse complète
else adresse déjà référencée
Client -> Commande : Selectionner une adresse
end
Commande --> Client : Formulaire de validation du paiement
Client -> Commande : Confirmer le choix de paiement par CB
Commande -> Banque : Redirection vers la banque
Banque --> Client : Formulaire de saisie des infos. carte bleue
Client -> Banque : Saisir informations de carte bancaire
alt paiement refusé par la banque
Commande --> Client : Message paiement refusé puis redirection à l'étape de validation du paiement
hnote right : ** FIN - retour à l'étape paiement **
end
Banque --> Commande : information de paiment Ok 
Commande -> Client : Redirection vers l'historique des commandes et message de confirmation de commande
Commande -> Client : Mail de confirmation de commande
@enduml