@startuml
title Création d'une commande : Valider la commande
actor Client
collections Application
control Server
database Order
boundary Bank
Client -> Application : Valider commande
hnote right : ** Liste des plats **
Application -> Server : orderValid(orderId) 
Server -> Order : updateOrder(orderId, userId, status = 'waiting_user')
alt if (UserLoggedIn() == FALSE)
Server -> Application : redirect(currenturl, orderId) Authentification
ref over Client, Application : Authentification
Application --> Server : userId
end
Server -> Order : updateOrder(orderId, userId, status = 'waiting_address')
Order --> Server : orderId
Server -> Application : redirect() Etape livraison
hnote left : **Etape livraison**
Application --> Client : Affichage du formulaire de livraison
Client -> Application : Saisie des information de livraison
Application -> Server : SetOrderDeliery(orderId, data[])
Server -> Order : updateOrder(orderId, address_data[], status = 'waiting_payment')
Order --> Server : orderId
loop IF BANK RESPONSE == KO
Server -> Application : redirect() page de confirmation de paiement
Application --> Client : Bouton confirmation de paiement
Client -> Application : Bouton payer !
Application -> Server : OrderPaymentUpdate()
Server -> Order : updateOrder(orderId, address_data[], status = 'waiting_payment')
Order -> Server : OrderId
Server -> Application : Payment Request Set Url
Application -> Bank : redirect() page de paiement de la banque
hnote right : **Page de paiement de la banque**
Bank --> Client : Affichage du formulaire de paiement
Client -> Bank : Saisie des informations de paiement
Bank --> Server : Bank Response on url Callbback
alt IF BANK RESPONSE == "KO" 
Server -> Order : updateOrder(orderId, payment_data[], status = 'payment_ko')
Order --> Server : orderId
Server -> Application : redirect to payment page
Application --> Client : message paiement KO 
else RESPONSE == "OK"
Server -> Order : updateOrder(orderId, payment_data[], status = 'waiting_delivery_man')
Order --> Server : orderId
Server -> Application : redirect to commands list
Application --> Client : Message d'atente réponse livreur
ref over Client, Application : Liste des commandes
end
end
@enduml