@startuml
title Ajout d’un plat du jour
actor Admin
collections Plats 
Admin -> Plats : Ajouter un plat du jour
Plats --> Admin : Liste des plats déjà existants
alt Plat déjà existant
Admin -> Plats : Selectionner un plat
else Nouveau plat
Admin -> Plats : Créer un nouveau plat
Plats --> Admin : Formulaire de création de plat
Admin -> Plats : Saisie du nom, prix, photo...
end
Plats --> Admin : Confirmation du choix du plat du jour

@enduml